### ISSUE TITLE
Some issues when I ran VCMSA

### ISSUE THREAD

**Issue by Pranav-Machingal** [clairemcwhite/vcmsa#9]
@clairemcwhite , Thank you for sharing the code for vcmsa.
I tried to align the first 25 sequences of each file in the `Quantest2/Test` directory with vcmsa
I used the following arguments with `prot_bert_bfd` model:
`vcmsa -i $in_file -o $align_file -l -1 -m $model_path --exclude -l2`

I faced the following issues when I tried this:

1.  For some files like `gtp.vie` , some residues of the input sequences were missing in the output alignment file. 
For eg: Input sequence was: 
 ```
>seq0001
MQTIKCVVVGDVAVGKTCLLISYTTNKFPSEYVPTVFDNYAVTVMIGGEPYTLGLFDTAGQEDYDRLRPLSYPQTDVFLVCFSVVSPSSFENVKEKWVPEITHHCPKTPFLLVGTQIDLRDDPSTIEKLAKNKQKPITPETAEKLARDLKAVKYVECSALTQKGLKNVFDEAILAALEPPEPKKSRRCVL
```
but output was:
```
>seq0001
M----------------QTV----VVGD-VAV-GKTCLLI--TTN-FPSEYVPT-VFDY--------AVTI---ETQEDYDR-LRPLSYPQTVLCFSVVSPS----------------------------S--------F-NVKEK-W--V---HPK-TPFL-L------------------------------------VGT-QDLRDDSTIEK-LAKNKQ--KPITPE-A-L-AKAVKY----------VECSALTQKG------LKNVFDE--AILAALEP-PP-----------------------------
```
2.  For some test files (around 30 of 151) like `FAD-oxidase_C` i got the following error:
```
File "/home/pranav.mac/anaconda3/envs/vcmsa_env/lib/python3.10/site-packages/igraph/clustering.py", line 832, in as_clustering
    membership = community_to_membership(self._merges, num_elts, num_elts - n)
igraph._igraph.InternalError: Error at src/community/community_misc.c:93: Number of steps is greater than number of rows in merges matrix: found 2
3 steps, 21 rows. -- Invalid value
```

**Comment by ntamas** [comment]
This is a bug in `igraph`, not in VCMSA (see https://github.com/igraph/python-igraph/issues/616 ). It has been fixed recently and the fix will be released in the next patch version of `python-igraph`.

**Comment by szhorvat** [comment]
It is useful to mention that this issue typically arises when the graph is disconnected.

**Comment by clairemcwhite** [comment]
I suspect that the missing amino acids is due to the alignment not completing after the maximum iterations, which is by default 100, controlled by  the --max_iterations parameter. In the latest update to the repository, I added that unaligned amino acids after the final iteration will be added to the alignment. 

```
vcmsa -i $in_file -o $align_file -l -1 -m $model_path --exclude -l2
```
FYI, the -l2 option was experimental, and I wouldn't recommend using it. Additionally, alignments with just the final layer tend to be poor. I'd suggest using the default final 16 layers. Generally the prot_t5_xl_uniref50 model works better as well.

**Comment by Pranav-Machingal** [comment]
@ntamas , @szhorvat , @clairemcwhite Thanks for the info and update.
